"use client";
import { FileSearchOutlined, FolderOpenOutlined } from "@ant-design/icons";
import { Card, Empty, Input, List, Space, Tag, Typography } from "antd";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import AppShell from "@/components/AppShell";
type Outcome = { id: string; title: string | null; submittedAt: string; summary: string | null; task: { id: string; title: string; status: "OPEN" | "CLOSED" }; updatedBy: { displayName: string }; assetCount: number; types: string[] };
const typeLabel: Record<string, string> = { IMAGE: "照片", VIDEO: "视频", DOCUMENT: "文档" };
export default function OutcomesPage() { const [items, setItems] = useState<Outcome[]>([]); const [loading, setLoading] = useState(true); const [q, setQ] = useState(""); useEffect(() => { fetch("/api/outcomes", { cache: "no-store" }).then((r) => r.json()).then((d) => setItems(d.outcomes ?? [])).catch(() => setItems([])).finally(() => setLoading(false)); }, []); const shown = useMemo(() => { const x = q.trim().toLowerCase(); return !x ? items : items.filter((o) => [o.title, o.task.title, o.summary, o.updatedBy.displayName].some((v) => v?.toLowerCase().includes(x))); }, [items, q]); return <AppShell title="成果档案"><Space direction="vertical" size={16} style={{ width: "100%" }}><Card><Typography.Title level={4} style={{ marginTop: 0 }}>成果档案</Typography.Title><Typography.Paragraph type="secondary">集中查询已归档的推文、海报、视频与其他活动材料。命名规范：姓名＋活动名称＋内容。</Typography.Paragraph><Input prefix={<FileSearchOutlined />} value={q} onChange={(e) => setQ(e.target.value)} placeholder="搜索档案名称、活动名称、提交人或说明" allowClear /></Card><Card bodyStyle={{ padding: 0 }}><List loading={loading} dataSource={shown} locale={{ emptyText: <Empty description="暂无成果档案" /> }} renderItem={(o) => <List.Item style={{ padding: "16px 20px" }}><List.Item.Meta avatar={<FolderOpenOutlined style={{ fontSize: 28, color: "#1677ff" }} />} title={<Space wrap><Link href={`/tasks/${o.task.id}`}>{o.title || `${o.updatedBy.displayName}+${o.task.title}+其他`}</Link><Tag color={o.task.status === "CLOSED" ? "default" : "blue"}>{o.task.status === "CLOSED" ? "已结束" : "进行中"}</Tag></Space>} description={<Space direction="vertical" size={3}><Typography.Text type="secondary">活动：{o.task.title} · 提交时间：{new Date(o.submittedAt).toLocaleString()} · 材料 {o.assetCount} 项</Typography.Text>{o.summary && <Typography.Text ellipsis={{ tooltip: o.summary }}>{o.summary}</Typography.Text>}<Space wrap>{o.types.map((t) => <Tag key={t}>{typeLabel[t]}</Tag>)}</Space></Space>} /></List.Item>} /></Card></Space></AppShell>; }
