import { NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { readSessionCookie } from "@/lib/auth";
type Params = { id: string };
const UpdateSchema = z.object({ summary: z.string().trim().max(5000).nullable().optional(), externalUrl: z.string().url().max(1000).nullable().optional(), externalLabel: z.string().trim().max(120).nullable().optional() });
const archiveInclude = { updatedBy: { select: { id: true, displayName: true } }, assets: { orderBy: [{ sort: "asc" as const }, { createdAt: "asc" as const }], include: { uploadedBy: { select: { id: true, displayName: true } } } } };
type ArchiveRecord = { id: string; summary: string | null; externalUrl: string | null; externalLabel: string | null; updatedAt: Date; updatedBy: { id: string; displayName: string }; assets: { id: string; kind: string; url: string; filename: string; mimeType: string; sizeBytes: number | null; createdAt: Date; uploadedBy: { id: string; displayName: string } }[] };
function serialize(outcome: ArchiveRecord | null) { if (!outcome) return null; return { id: outcome.id, summary: outcome.summary, externalUrl: outcome.externalUrl, externalLabel: outcome.externalLabel, updatedAt: outcome.updatedAt.toISOString(), updatedBy: outcome.updatedBy, assets: outcome.assets.map((a) => ({ id: a.id, kind: a.kind, url: a.url, filename: a.filename, mimeType: a.mimeType, sizeBytes: a.sizeBytes, createdAt: a.createdAt.toISOString(), uploadedBy: a.uploadedBy })) }; }
export async function GET(_req: Request, ctx: { params: Promise<Params> }) { const session = await readSessionCookie(); if (!session) return NextResponse.json({ message: "未登录" }, { status: 401 }); const { id: taskId } = await ctx.params; const outcome = await prisma.taskOutcome.findUnique({ where: { taskId }, include: archiveInclude }); return NextResponse.json({ outcome: serialize(outcome) }); }
/** 管理员/部长维护可见给全体成员的成果说明与成品链接。 */
export async function PATCH(req: Request, ctx: { params: Promise<Params> }) { const session = await readSessionCookie(); if (!session) return NextResponse.json({ message: "未登录" }, { status: 401 }); if (session.role !== "ADMIN" && session.role !== "MINISTER") return NextResponse.json({ message: "仅管理人员可编辑成果说明" }, { status: 403 }); const { id: taskId } = await ctx.params; const exists = await prisma.task.findUnique({ where: { id: taskId }, select: { id: true } }); if (!exists) return NextResponse.json({ message: "任务不存在" }, { status: 404 }); const parsed = UpdateSchema.safeParse(await req.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ message: parsed.error.issues[0]?.message ?? "参数错误" }, { status: 400 }); const d = parsed.data; const outcome = await prisma.taskOutcome.upsert({ where: { taskId }, create: { taskId, updatedById: session.sub, summary: d.summary || null, externalUrl: d.externalUrl || null, externalLabel: d.externalLabel || null }, update: { updatedById: session.sub, summary: d.summary || null, externalUrl: d.externalUrl || null, externalLabel: d.externalLabel || null }, include: archiveInclude }); return NextResponse.json({ outcome: serialize(outcome) }); }
